platform :ios, '17.0'

inhibit_all_warnings!

target 'LiteDineGuideDemo' do
  use_frameworks!

  pod 'AMapFoundation-NO-IDFA', '~> 1.8'
  pod 'AMap3DMap-NO-IDFA', '~> 11.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end

  Dir.glob(File.join(installer.sandbox.root, 'Target Support Files/**/*.xcconfig')).each do |path|
    text = File.read(path)
    text = text.gsub(/^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\].*\n/, '')
    text << "EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64\n"
    File.write(path, text)
  end
end
